### PR TITLE
[RFC] Chainable resolvers 

### LINKED ISSUE #24: Chapter 1) The Router API
# The router API

## Challenges with the current implementation

- TypeScript performance. Each procedure added creates a new Router that TypeScript chokes on as the underlying complexity grows non-linearly with each added procedure - each procedure basically has its "own instance" within the compiler even if it's flattened and unaffected at runtime.
- I find that those queries are hard/unintuitive to write, I find myself counting parentheses and curly brackets all too often. Arguably, your suggestions with the resolver API could also address this.
- No CMD+click

## Suggested implementation

- Flat router
- No automatic prefixing (breaks jump to definition / CMD+click)

```tsx
import { z } from 'zod';
import { initTRPC } from './trpc/server';

const trpc = initTRPC<Context>();

const postRouter = trpc.router({
  queries: {
    postById: null as any /* resolver implementation is a separate discussion */
    postAll: null as any /* resolver implementation is a separate discussion */
  },
  mutations: {
   postAdd: null as any /* resolver implementation is a separate discussion */
});

const userRouter = trpc.router({
  queries: {
    userAll: null as any /* resolver implementation is a separate discussion */
  },
);

const appRouter = trpc.mergeRouters(
  postRouter, 
  userRouter, 
  // ...
)
```

### LINKED ISSUE #25: Chapter 2) The Resolver API + middlewares
# The Resolver API and middlewares

## Problems with the current implementation

- Middlewares are hard to reuse
- I find them quite fiddly to write - counting brackets etc.

### Standalone route
```tsx
// single resolver
const myProcedure = trpc.resolver(
  trpc.zod( z.object({ id: z.string }) ),
  ({ ctx, input }) => {
    return 'my data goes here'
  }
)```

### In a router
```ts
export const appRouter = trpc.router({
  queries: {
    // procedure with input validation called `greeting`
    greeting: trpc.resolver(
      trpc.zod(
        z.object({
          hello: z.string(),
        }),
      ),
      (params) => {
        return {
          data: {
            greeting: 'hello ' + params.ctx.user?.id ?? params.input.hello,
          },
        };
      },
    ),
  }
)
```

### Inferring errors

```ts
const isAuthed = trpc.newContext((params) => {
  if (!params.ctx.user) {
    return {
      error: {
        code: 'UNAUTHORIZED',
      },
    };
  }
  return {
    ctx: {
      ...params.ctx,
      user: params.ctx.user,
    },
  };
});

```

### Reusable middleware

```ts
// with re-usable middleware
const isAuthed = trpc.newContext((params) => {
  if (!params.ctx.user) {
    return {
      error: {
        code: 'UNAUTHORIZED',
      },
    };
  }
  return {
    ctx: {
      ...params.ctx,
      user: params.ctx.user,
    },
  };
});

export const appRouter = trpc.router({
  queries: {
    // procedure with input validation called `greeting`
    postCreate: trpc.resolver(
       isAuthed,
      (params) => {
        return {
           // ...
        };
      },
    ),
  }
)
```

### Standalone route
```tsx
// single resolver
const myProcedure = trpc.route(route => route
  .input(z.object({hello: z.string}))
  .resolve(req => {
    return req.input.hello;
  })
);
```

### In a router
```ts
export const appRouter = trpc.router({
  queries: {
    // procedure with input validation called `greeting`
    greeting: route => route
      .input(
        z.object({
          hello: z.string(),
        })
      )
      .resolve(req => {
        return {
          data: {
            greeting: 'hello ' + params.ctx.user?.id ?? params.input.hello,
          },
        };
      }),
  },
});
```

### Reusable middleware

```ts
// with re-usable middleware
const isAuthed = trpc.middleware(params => {
  if (!params.ctx.user) {
    return trpc.error({
        code: 'UNAUTHORIZED',
    });
  }
  return {
    ctx: {
      ...params.ctx,
      user: params.ctx.user,
    },
  };
});


export const appRouter = trpc.router({
  queries: {
    // procedure with input validation called `greeting`
    postCreate: route => route
      .use(isAuthed)
      .resolve(params => {
        return {
          // ...
        };
      }),
  },
});
```

### PR DESCRIPTION
**Pull request by KATT**
I've let this marinate, and I think chaining for the resolver API could be nicer. I've here created a POC that you can compare side-by-side with the `main` branch. Closes #25 & Closes #24.

## Notes

- I have decided to not ship inferrable errors for the first iteration.
- You will be able to CMD+Click from the client/React component and jump straight to your backend definition
- Ignore that it's `throw Error`  below; imagine `throw TRPCError({ code: '..'})`
- You can now define `input` before or after your middlewares run, it's up to you!
- Considerable performance improvements of the TypeScript compilation - compiling a router with **3,000** procedures with inlined Zod-schemas takes ~10 seconds in CI.
- **Playground 👉**   https://stackblitz.com/github/trpc/v10-playground/tree/katt/procedure-chains?file=src%2Fserver.ts (note that it's only TypeScript ergonomics, no actual implementation yet)

### §1.0 Setting up tRPC

```tsx
type Context = {
  user?: {
    id: string;
    memberships: {
      organizationId: string;
    }[];
  };
};

const trpc = initTRPC<Context>();

const {
  /**
   * Builder object for creating procedures
   */
  procedure,
  /**
   * Create reusable middlewares
   */
  middleware,
  /**
   * Create a router
   */
  router,
  /**
   * Merge Routers
   */
  mergeRouters,
} = trpc;
```

### §1.1 Creating a router

```tsx
export const appRouter = trpc.router({
  queries: {
    // [...]
  },
  mutations: {
    // [...]
  },
})
```

### §1.2 Defining a procedure

```tsx
export const appRouter = trpc.router({
  queries: {
    // simple procedure without args avialable at postAll`
    postList: procedure.resolve(() => postsDb),
  }
});
```

#### Details about the procedure builder

Simplified to be more readable - see full implementation in https://github.com/trpc/v10-playground/blob/katt/procedure-chains/src/trpc/server/procedure.ts

```tsx

interface ProcedureBuilder {
  /**
   * Add an input parser to the procedure.
   */
  input(
    schema: $TParser,
  ): ProcedureBuilder;
  /**
   * Add an output parser to the procedure.
   */
  output(
    schema: $TParser,
  ): ProcedureBuilder;
  /**
   * Add a middleware to the procedure.
   */
  use(
    fn: MiddlewareFunction<TParams, $TParams>,
  ): ProcedureBuilder
  /**
   * Extend the procedure with another procedure
   */
  concat(
    proc: ProcedureBuilder,
  ): ProcedureBuilder;
  resolve(
    resolver: (
      opts: ResolveOptions<TParams>,
    ) => $TOutput,
  ): Procedure;
}
```

### §1.3 Adding input parser

> Note that I'll skip the `trpc.router({ queries: /*...*/})` below here

```tsx

// get post by id or 404 if it's not found
const postById = procedure
  .input(
    z.object({
      id: z.string(),
    }),
  )
  .resolve(({ input }) => {
    const post = postsDb.find((post) => post.id === input.id);
    if (!post) {
      throw new Error('NOT_FOUND');
    }
    return {
      data: postsDb,
    };
  });
```

### §1.4 Procedure with middleware

```tsx
const whoami = procedure
  .use((params) => {
    if (!params.ctx.user) {
      throw new Error('UNAUTHORIZED');
    }
    return params.next({
      ctx: {
        // User is now set on the ctx object
        user: params.ctx.user,
      },
    });
  })
  .resolve(({ ctx }) => {
    // `isAuthed()` will propagate new `ctx`
    // `ctx.user` is now `NonNullable`
    return `your id is ${ctx.user.id}`;
  });
 
```

### §2.1 Define a reusable middleware

```tsx

const isAuthed = trpc.middleware((params) => {
  if (!params.ctx.user) {
    throw new Error('zup');
  }
  return params.next({
    ctx: {
      user: params.ctx.user,
    },
  });
});

// Use in procedure:
const whoami = procedure
  .use(isAuthed)
  .resolve(({ ctx }) => {
    // `isAuthed()` will propagate new `ctx`
    // `ctx.user` is now `NonNullable`
    return `your id is ${ctx.user.id}`;
  });
```

### §2.2 Create a bunch of procedures that are all protected

```tsx
const protectedProcedure = procedure.use(isAuthed);

export const appRouter = trpc.router({
  queries: {
    postList: protectedProcedure.resolve(() => postsDb),
    postById: protectedProcedure
      .input(
        z.object({
          id: z.string(),
        }),
      )
      .resolve(({ input }) => {
        const post = postsDb.find((post) => post.id === input.id);
        if (!post) {
          throw new Error('NOT_FOUND');
        }
        return {
          data: postsDb,
        };
      })
 }
})
```

### §2.3 Define an `output` schema

```tsx
procedure
      .output(z.void())
      // This will fail because we've explicitly said this procedure is `void`
      .resolve(({ input }) => {
        return'hello';
      })
```

### §2.4 Merging routers

```ts
const postRouter = trpc.router({
  queries: {
    postList: protectedProcedure.resolve(() => postsDb),
    postById: protectedProcedure
      .input(
        z.object({
          id: z.string(),
        }),
      )
      .resolve(({ input }) => {
        const post = postsDb.find((post) => post.id === input.id);
        if (!post) {
          throw new Error('NOT_FOUND');
        }
        return {
          data: postsDb,
        };
      })
  }
})

const health = trpc.router({
  query: {
    healthz: trpc.resolve(() => 'I am alive')
  }
})

export const appRouter = trpc.mergeRouters(
  postRouter,
  health
);
```

### Compose dynamic combos of middlewares/input parsers

```tsx

/**
 * A reusable combination of an input + middleware that can be reused.
 * Accepts a Zod-schema as a generic.
 */
function isPartOfOrg<
  TSchema extends z.ZodObject<{ organizationId: z.ZodString }>,
>(schema: TSchema) {
  return procedure.input(schema).use((params) => {
    const { ctx, input } = params;
    const { user } = ctx;
    if (!user) {
      throw new Error('UNAUTHORIZED');
    }

    if (
      !user.memberships.some(
        (membership) => membership.organizationId !== input.organizationId,
      )
    ) {
      throw new Error('FORBIDDEN');
    }

    return params.next({
      ctx: {
        user,
      },
    });
  });
}



const editOrganization = procedure
  .concat(
    isPartOfOrg(
      z.object({
        organizationId: z.string(),
        data: z.object({
          name: z.string(),
        }),
      }),
    ),
  )
  .resolve(({ ctx, input }) => {
    // - User is guaranteed to be part of the organization queried
    // - `input` is of type:
      // {
      //   data: {
      //       name: string;
      //   };
      //   organizationId: string;
      // }

    // [.... insert logic here]
  });
```

### CODE REVIEW

File: src/server.ts [hunk 1]
```diff
@@ -68,59 +97,90 @@ export const appRouter = trpc.router({
...
+        isPartofOrg(
+          z.object({
+            organizationId: z.string(),
+            data: z
+              .object({
+                name: z.string(),
+              })
+              .partial(),
+          }),
+        ),
```
Comment (KATT) [inline src/server.ts]: I don't love the name `.apply()` here - any ideas for something better?

File: src/trpc/server/initTRPC.ts [hunk 2]
```diff
@@ -1,31 +1,24 @@
...
+import { createMiddlewareFactory } from './middleware';
 
 export function initTRPC<TContext>() {
   return {
     /**
-     * Create procedure resolver
+     * Builder object for creating procedures
      */
-    resolver: pipedResolver<TContext>(),
+    procedure: createProcedure<TContext>(),
```
Comment (KATT) [inline src/trpc/server/initTRPC.ts]: Should this be called `builder` or something else perhaps?

**Review by KATT — COMMENTED** [review]
Some minor naming things I'd like input on.

File: src/server.ts (hunk 1 above)
Comment (sachinraja) [reply src/server.ts]: I think it largely depends on the way it will be used, but it feels like a sort of plugin to me. Maybe  `.register` ([like Fastify](https://www.fastify.io/docs/latest/Reference/Plugins/))?

File: src/trpc/server/initTRPC.ts (hunk 2 above)
Comment (sachinraja) [reply src/trpc/server/initTRPC.ts]: I think `procedure` is fine, maybe `procedureBuilder` if you want to be more clear about what it is, although I think it's clear enough already.

Comment (mmkal) [reply src/trpc/server/initTRPC.ts:10]: Could `.from` make sense? Like you’re building a procedure from another [partial] procedure [builder]?

File: src/server.ts (hunk 1 above)
Comment (mmkal) [reply src/server.ts]: Could `.from(…)` make sense? Like you’re building a procedure from another [partial] procedure [builder]?

Comment (KATT) [reply src/server.ts]: Or maybe `.assign()` or `.extend()` as it works similarly to `Object.assign()`

Comment (KATT) [reply src/server.ts]: I made it part of the `.use()`-fn! How does that feel to you?

Comment (KATT) [reply src/server.ts]: Or maybe `concat` would be a good word too, like `[].concat`. Probably less confusing if I have it separate to `use`

Comment (KATT) [reply src/server.ts]: Anywayyyy I shouldn't get stuck on naming, can be changed easily with deprecation

Comment (mmkal) [reply src/server.ts]: Merging easier than splitting though! I’d be basically fine with any of the above but agree that overloading use could be confusing.

File: src/trpc/server/Params.ts [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+  _output_out: TOutputOut;
+  /**
+   * @internal
+   */
+  _input_in: TInputIn;
+  /**
+   * @internal
+   */
+  _input_out: TInputOut;
+}
```
Comment (KATT) [inline src/trpc/server/Params.ts]: @mmkal I guess this is what you referred to as an options-bag? :)

Comment (mmkal) [reply src/trpc/server/Params.ts]: Tried to write a reply to this on my phone but too hard! Yes this is pretty much what I was thinking. A couple of ways it could be simplified even further occur to me tho:

1. No linear generics at _all_. This might prove impossible if the compiler loses track of property types somewhere along the way, but here's a simplified example:

```ts
interface Params {
  input: unknown
  output: unknown
  context: unknown
}

const getClientThatUsesSpecificParams = <P extends Params>(params: P) => {
  return {
    useInput: (input: P['input']) => 123,
    getOutput: () => params.output,
  }
}

const specific = getClientThatUsesSpecificParams({
  input: {foo: 'abc'},
  output: [123, 456],
  context: {bar: 987},
})
```

TypeScript doesn't need specific typeargs for `TInput`, `TOutput`, `TContext` to keep track of them:

image

2. Maybe there could be an IO type to generalise the `_in` and `_out` suffixes?

```ts
interface IO<I, O> {
  in: I
  out: O
}

interface Params< 
  TContextIn = unknown,
  TContextOut = unknown,
  TInputIn = unknown,
  TInputOut = unknown,
  TOutputIn = unknown,
  TOutputOut = unknown,
> {
  ctx: IO<TContextIn, TContextOut>
  input: IO<TInputIn, TInputOut>
  output: IO<TOutputIn, TOutputOut>
}
```

3. Both together!?!!?

```ts
interface IO {
  input: unknown
  output: unknown
}

interface Params {
  ctx: IO
  input: IO
  output: IO
}
```

**Comment by mmkal** [comment]
I love this

File: src/trpc/server/Params.ts (hunk 3 above)
Comment (KATT) [reply src/trpc/server/Params.ts]: Made #35. Feel free to do PR, I have some decent testing and it's easy to run with yarn dev.

These are all internal types so easy to refactor later too, but would be nice to have it clean

**Comment by yume-chan** [comment]
It looks so good! I only have two minor questions:

1. Will `mergeRouters` accept `prefix` like it does now, like

```ts
export const appRouter = trpc.mergeRouters({
  post: postRouter
}, health);
```

2. Is it possible to `concat` mutliple `input`s? For example maybe I have another `isPartOfTeam` input + middleware, and I want to use it with `isPartOfOrg`? If yes, will the order of `input` and `use` affect the actual validation? Say in `procedure.input(a).use(b).input(c).resolve(d)`, both `b` and `c` will fail, what error would be returned?
