### PR TITLE
repro of issue

### LINKED ISSUE #1: Inferring the right error on `contextSwapperMiddleware`
## Steps to reproduce

1. Comment out https://github.com/KATT/trpc-procedure-play/blob/b9ea789c7c34e3ca12dea432856158d2c7753873/src/server.ts#L69-L85
2. Re-enable https://github.com/KATT/trpc-procedure-play/blob/b9ea789c7c34e3ca12dea432856158d2c7753873/src/server.ts#L68

### Expected

`result` at https://github.com/KATT/trpc-procedure-play/blob/b9ea789c7c34e3ca12dea432856158d2c7753873/src/server.ts#L107 should return the `UNAUTHORIZED` as part of the errors

### Actual

`result` is `ResultError | [...]`

### PR DESCRIPTION
**Pull request by KATT**
**UPDATE:** fixed in 7b61710 - closes #1

Please note that alternative solutions to the same problem are welcome too. 

---

- Repro of #1
- See comment https://github.com/KATT/trpc-procedure-play/pull/2#discussion_r787265239
- Go to https://codesandbox.io/s/github/KATT/trpc-procedure-play/tree/katt/issue-showcase?file=/src/server.ts 
- Try to get rid of the red squiggly lines
  - we probably need to modify `contextSwapperMiddleware` somehow.

### CODE REVIEW

File: src/server.ts [hunk 1]
```diff
@@ -99,44 +81,87 @@ export const appRouter = createRouter({
         };
       },
     ),
+    whoami: resolver(
+      // FIXME this doesn't work as epxected:
+      isAuthed(),
```
Comment (KATT) [inline src/server.ts]: This doesn't work

File: src/server.ts [hunk 2]
```diff
@@ -99,44 +81,87 @@ export const appRouter = createRouter({
...
+      //     };
+      //   }
+      //   return params.next({
+      //     ...params,
+      //     ctx: {
+      //       ...params.ctx,
+      //       user: params.ctx.user,
+      //     },
+      //   });
+      // },
```
Comment (KATT) [inline src/server.ts]: This works how I want `isAuthed()` to work
